promise.then(f1).catch(f2);
promise.then(f1, f2);

// Есть различия: первый - обработка ошибки, а во втором её нет
